version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - desafio-net

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - desafio-net

volumes:
  redis_data:

networks:
  desafio-net:
    driver: bridge